/* ui.js — KPI strip, assumptions panel, methodology, CSV export. */

const UI = (() => {

  /* ---------------- AI overnight summary ----------------
     Renders data/overnight_summary.json (written by
     ops/run_overnight_summary.sh via the dashboard-watcher agent). This is
     model-generated interpretation, not a data series — all strings are
     escaped before injection and the panel is badged AI-generated. */

  function esc(value) {
    return String(value).replace(/[&<>"]/g, (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  }

  function renderOvernight() {
    const body = document.getElementById("overnight-body");
    const metaLine = document.getElementById("overnight-meta");
    if (!body) return;
    // GB-only analysis: hide the card entirely on other zones rather than
    // showing a misleading "not yet available" message.
    document.getElementById("overnight").classList
      .toggle("hidden", State.get().zone !== "GB");
    const s = Data.overnight;
    if (!s || !s.summary) {
      metaLine.textContent = "";
      body.innerHTML = `<p class="overnight-empty">Overnight summary not yet
        available — it is generated by
        <code>ops/run_overnight_summary.sh</code> as part of the daily
        refresh.</p>`;
      return;
    }
    const win = s.window || {};
    metaLine.textContent = [
      win.from && win.to
        ? `${Metrics.fmtDate(win.from, "datetime")} → ` +
          `${Metrics.fmtDate(win.to, "datetime")} UTC`
        : null,
      s.baseline_days ? `baseline ${s.baseline_days} d` : null,
      s.generated_at
        ? `generated ${Metrics.fmtDate(s.generated_at, "datetime")} UTC`
        : null,
    ].filter(Boolean).join(" · ");

    const anomalies = Array.isArray(s.anomalies) ? s.anomalies : [];
    const dq = Array.isArray(s.data_quality) ? s.data_quality : [];
    body.innerHTML = `
      <p class="overnight-summary">${esc(s.summary)}</p>
      <div class="overnight-block">
        <span class="overnight-h">Anomalies</span>
        ${anomalies.length
          ? `<ul class="overnight-list">${anomalies.map((a) =>
              `<li><b>${esc(a.metric)}</b>` +
              (a.value != null ? ` ${esc(a.value)}` : "") +
              (a.z != null
                ? ` <span class="mono-dim">(z=${esc(a.z)})</span>` : "") +
              (a.hypothesis ? ` — ${esc(a.hypothesis)}` : "") +
              "</li>").join("")}</ul>`
          : `<span class="overnight-none">No anomalies detected
             (|z| ≤ 2 across tracked metrics).</span>`}
      </div>
      <div class="overnight-block">
        <span class="overnight-h">Data quality</span>
        ${dq.length
          ? `<ul class="overnight-list">${dq.map((f) =>
              `<li>${esc(f)}</li>`).join("")}</ul>`
          : `<span class="overnight-none">No flags.</span>`}
      </div>
      <p class="overnight-foot">Generated by an LLM (dashboard-watcher agent)
         from the published dataset — an interpretation, not an observed or
         estimated data series.</p>`;
  }

  /* ---------------- "At a glance" summary bar ----------------
     Four headline figures pulled from values/formulas that already exist
     elsewhere on the dashboard — nothing is computed differently here. */

  function renderGlance() {
    const el = document.getElementById("glance");
    if (!el) return;
    const items = [];

    const cur = Data.currency(); // per-zone, read from meta
    const price = Data.latest("price");
    if (price) items.push({ label: "Price",
      value: `${cur}${price.value.toFixed(1)}`,
      unit: "/MWh", badge: "observed" });

    // Clean spark spread: same formula as the Spreads tab, latest day with
    // all three inputs present. GB only — other zones carry no gas/carbon.
    const d = Data.daily;
    const a = State.get().assumptions;
    for (let i = (d.gas_sap && d.carbon_uka_month) ? d.d.length - 1 : -1;
         i >= 0; i--) {
      if (d.price[i] != null && d.gas_sap[i] != null
          && d.carbon_uka_month[i] != null) {
        const spark = Metrics.cleanSparkSpread([d.price[i]], [d.gas_sap[i]],
          [d.carbon_uka_month[i]], a)[0];
        if (spark != null) items.push({ label: "Clean spark",
          value: `£${spark.toFixed(1)}`, unit: "/MWh", badge: "estimated" });
        break;
      }
    }

    // Low-carbon share at the latest half-hour — the low-carbon chart's
    // formula applied to the most recent index.
    const hh = Data.hh;
    const idx = Data.latest("demand")?.index;
    if (idx != null) {
      const sum = (keys) => keys.filter((k) => hh[k])
        .reduce((s, k) => s + Math.max(hh[k][idx] ?? 0, 0), 0);
      const low = sum(Data.LOW_CARBON);
      const total = sum(Data.STACK_ORDER)
        + Math.max(hh.netImports[idx] ?? 0, 0);
      if (total > 0) items.push({ label: "Low-carbon",
        value: `${Math.round((100 * low) / total)}`, unit: "%",
        badge: "estimated" });
    }

    const hasFlows = Object.keys(Data.INTERCONNECTORS)
      .some((k) => Data.hh[k]);
    const net = hasFlows ? Data.latest("netImports") : null;
    if (net) {
      const gw = net.value / 1000;
      items.push({ label: gw >= 0 ? "Net imports" : "Net exports",
        value: Math.abs(gw).toFixed(1), unit: "GW", badge: "observed" });
    }

    el.innerHTML = items.map((it) => `<div class="glance-item">
      <span class="g-label">${it.label}
        <span class="g-dot ${it.badge}" title="${it.badge}"></span></span>
      <span class="g-value">${it.value}<small>${it.unit}</small></span>
    </div>`).join("");
  }

  /* ---------------- KPI strip ---------------- */

  function kpiCard({ label, badge, value, unit, delta, deltaLabel, note }) {
    const dirClass = delta == null ? "neutral" : delta > 0 ? "up" : "down";
    const arrow = delta == null ? "" : delta > 0 ? "▲" : "▼";
    return `<div class="kpi">
      <div class="k-label"><span>${label}</span>
        <span class="badge ${badge}">${badge}</span></div>
      <div class="k-value">${value}<small> ${unit}</small></div>
      ${delta != null ? `<div class="k-delta ${dirClass}">${arrow} ${
        Math.abs(delta).toFixed(1)} ${deltaLabel}</div>` : ""}
      ${note ? `<div class="k-note">${note}</div>` : ""}
    </div>`;
  }

  function renderKpis() {
    const hh = Data.hh;
    const price = Data.latest("price");
    const i = price.index;
    const back48 = Math.max(0, i - 48);
    const cards = [];

    const dayAgo = hh.price[back48];
    const cur = Data.currency(); // per-zone, read from meta
    cards.push(kpiCard({
      label: "Power price", badge: "observed",
      value: `${cur}${price.value.toFixed(1)}`, unit: "/MWh",
      delta: dayAgo == null ? null : price.value - dayAgo,
      deltaLabel: "vs 24h ago",
    }));

    const demand = Data.latest("demand");
    cards.push(kpiCard({
      label: "Demand", badge: "observed",
      value: (demand.value / 1000).toFixed(1), unit: "GW",
    }));

    // Wind/solar cards only where the zone actually reports the series
    // (e.g. NO_2 and IE publish no solar type — all-null column).
    const wind = Data.hasSignal("WIND") ? Data.latest("WIND") : null;
    if (wind) {
      const windShare = wind.value / demand.value * 100;
      cards.push(kpiCard({
        label: "Wind", badge: "observed",
        value: (wind.value / 1000).toFixed(1), unit: "GW",
        note: `${windShare.toFixed(0)}% of demand ${State.get().zone === "GB"
          ? "(transmission only)" : "(on+offshore — ENTSO-E)"}`,
      }));
    }

    // hasSignal also drops constant-zero TSO placeholders (e.g. IE solar
    // — reported as 0 for fleet the TSO does not meter; see data_quality)
    const solar = Data.hasSignal("solar") ? Data.latest("solar") : null;
    if (solar) {
      cards.push(kpiCard({
        label: "Solar", badge: "observed",
        value: (solar.value / 1000).toFixed(1), unit: "GW",
        note: State.get().zone === "GB"
          ? "PV_Live national estimate" : "ENTSO-E TSO-published",
      }));
    }

    // Only meaningful when interconnector columns exist (GB): for ENTSO-E
    // zones netImports is all zeros because flows are not fetched.
    if (Object.keys(Data.INTERCONNECTORS).some((k) => Data.hh[k])) {
      const net = Data.latest("netImports");
      cards.push(kpiCard({
        label: "Net imports", badge: "observed",
        value: (net.value / 1000).toFixed(1), unit: "GW",
        note: net.value >= 0 ? "importing" : "exporting",
      }));
    }

    const gas = Data.latestDaily("gas_sap");
    if (gas) {
    const gasIdx = gas.index;
    const gasPrev = gasIdx > 0 ? Data.daily.gas_sap[gasIdx - 1] : null;
    cards.push(kpiCard({
      label: "Gas SAP", badge: "observed",
      value: `£${gas.value.toFixed(1)}`, unit: "/MWh th",
      delta: gasPrev == null ? null : gas.value - gasPrev,
      deltaLabel: "vs prior gas day",
      note: Metrics.fmtDate(gas.d, "day"),
    }));
    }

    const carbon = Data.latestDaily("carbon_uka_month");
    if (carbon) {
    const ffilled = (Data.daily.carbon_ffill || [])[carbon.index];
    cards.push(kpiCard({
      label: "Carbon (UKA)", badge: ffilled ? "estimated" : "observed",
      value: `£${carbon.value.toFixed(2)}`, unit: "/tCO2",
      note: ffilled
        ? `carried fwd from ${Metrics.fmtDate(
            Data.meta.coverage.carbon_last_observed_month + "-01", "month")}`
        : "official monthly average",
    }));
    }

    const coal = State.coalInfo();
    if (coal && coal.source === "proxy") {
      cards.push(kpiCard({
        label: "Coal proxy", badge: "proxy",
        value: `£${coal.value.toFixed(1)}`, unit: "/MWh th",
        note: coal.ffilled
          ? `carried fwd from ${Metrics.fmtDate(
              Data.meta.coverage.coal_last_observed_month + "-01", "month")}`
          : "Newcastle futures, WB monthly avg",
      }));
    }

    if (State.get().zone === "GB") {
    // Residual-load definitions are zone-specific (see plan/04) — GB only.
    const residual = (demand.value - wind.value) / 1000;
    cards.push(kpiCard({
      label: "Residual load", badge: "estimated",
      value: residual.toFixed(1), unit: "GW",
      note: "demand − wind (INDO already nets off embedded gen)",
    }));
    }

    document.getElementById("kpi-strip").innerHTML = cards.join("");
  }

  /* ---------------- assumptions panel ---------------- */

  const SLIDERS = [
    { key: "eta", label: "Reference CCGT efficiency (spreads)",
      min: 0.35, max: 0.62, step: 0.01, fmt: (v) => (v * 100).toFixed(0) + "%",
      note: "HHV basis. 49–52% is typical for the modern GB fleet." },
    { key: "etaCcgtLow", label: "CCGT fleet efficiency — low end",
      min: 0.35, max: 0.55, step: 0.01, fmt: (v) => (v * 100).toFixed(0) + "%" },
    { key: "etaCcgtHigh", label: "CCGT fleet efficiency — high end",
      min: 0.45, max: 0.62, step: 0.01, fmt: (v) => (v * 100).toFixed(0) + "%" },
    { key: "efGas", label: "Gas carbon intensity",
      min: 0.18, max: 0.21, step: 0.001, fmt: (v) => v.toFixed(3) + " t/MWh th",
      note: "UK inventory factor ≈ 0.184 tCO2/MWh (HHV)." },
    { key: "vom", label: "CCGT variable O&M",
      min: 0, max: 10, step: 0.5, fmt: (v) => "£" + v.toFixed(1) + "/MWh" },
    { key: "etaOcgtLow", label: "OCGT efficiency — low end",
      min: 0.25, max: 0.38, step: 0.01, fmt: (v) => (v * 100).toFixed(0) + "%" },
    { key: "etaOcgtHigh", label: "OCGT efficiency — high end",
      min: 0.32, max: 0.45, step: 0.01, fmt: (v) => (v * 100).toFixed(0) + "%" },
    { key: "etaCoal", label: "Coal efficiency (dark spread)",
      min: 0.30, max: 0.42, step: 0.01, fmt: (v) => (v * 100).toFixed(0) + "%" },
  ];

  function renderAssumptions() {
    const a = State.get().assumptions;
    document.getElementById("assumption-controls").innerHTML =
      SLIDERS.map((s) => `
        <div class="asm">
          <div class="asm-label"><span>${s.label}</span>
            <b id="asm-val-${s.key}">${s.fmt(a[s.key])}</b></div>
          <input type="range" data-asm="${s.key}" min="${s.min}" max="${s.max}"
                 step="${s.step}" value="${a[s.key]}">
          ${s.note ? `<div class="asm-note">${s.note}</div>` : ""}
        </div>`).join("");
    document.querySelectorAll("#assumption-controls input[type=range]")
      .forEach((input) => {
        input.addEventListener("input", (event) => {
          const key = event.target.dataset.asm;
          const value = parseFloat(event.target.value);
          const slider = SLIDERS.find((s) => s.key === key);
          document.getElementById(`asm-val-${key}`).textContent =
            slider.fmt(value);
          State.setAssumption(key, value);
        });
      });
  }

  /* ---------------- methodology ---------------- */

  /* ENTSO-E production types → dashboard columns, with the honest
     mismatches (mirrors plan/04-europe-extension.md). Shown on the
     Methodology tab for non-GB zones only. */
  const ENTSOE_FUEL_MAP = [
    ["Fossil Gas (B04)", "Gas (CCGT)", "ENTSO-E does not split CCGT/OCGT — "
      + "the OCGT column stays empty and per-technology merit assumptions "
      + "do not transfer"],
    ["Fossil Hard coal + Brown coal (B05, B02)", "Coal", "comparable"],
    ["Nuclear (B14)", "Nuclear", "comparable"],
    ["Wind Onshore + Offshore (B19, B18)", "Wind", "includes onshore — "
      + "GB's WIND is transmission-metered only, so wind shares are not "
      + "directly comparable across zones"],
    ["Solar (B16)", "Solar", "TSO-published outturn — GB solar is a "
      + "PV_Live model estimate; same concept, different provenance"],
    ["Hydro Run-of-river + Reservoir (B11, B12)", "Hydro",
     "comparable in aggregate"],
    ["Hydro Pumped Storage (B10)", "Pumped storage", "comparable"],
    ["Biomass (B01)", "Biomass", "comparable"],
    ["Fossil Oil (B06)", "Oil", "comparable"],
    ["everything else", "Other", "explicit catch-all"],
  ];

  function renderZoneMethodology() {
    const meta = Data.meta;
    const zone = State.get().zone;
    const info = Data.ZONE_INFO[zone] || { label: zone, kind: "" };
    const sourceRows = Object.values(meta.series).map((s) => `
      <tr><td><b>${s.name}</b></td><td>${s.source}</td>
      <td>${s.unit}</td><td>${s.resolution}</td>
      <td>${s.quality}</td>
      <td>${s.notes || ""}</td></tr>`).join("");
    const mapRows = ENTSOE_FUEL_MAP.map(([from, to, note]) => `
      <tr><td>${from}</td><td><b>${to}</b></td><td>${note}</td></tr>`)
      .join("");

    document.getElementById("methodology-body").innerHTML = `
      <h3 id="m-window">Zone: ${info.label} (${zone})</h3>
      <p>${info.kind === "reference"
        ? "<b>Reference market — not physically interconnected with GB.</b> "
          + "Included as the European price anchor for context; do not read "
          + "GB flow implications into it."
        : "One of GB's physical counterparty bidding zones (direct "
          + "interconnection)."}
         Window: <code>${meta.window.start}</code> →
         <code>${meta.window.end}</code>, built
         <code>${meta.built_at}</code>. ${meta.timezone}
         Settlement currency as reported by ENTSO-E:
         <code>${meta.currency}</code>.</p>

      <h3 id="m-sources">Data sources (this zone)</h3>
      <p>Everything below comes from the <b>ENTSO-E Transparency
         Platform</b> (free, token-gated API) — unlike GB, which uses
         Elexon, PV_Live, National Gas and gov.uk. All series are
         <b>Observed</b>: TSO-published outturns and the day-ahead auction
         price (a true auction price, unlike GB's MID proxy).</p>
      <table><tr><th>Series</th><th>Source / document</th><th>Unit</th>
        <th>Resolution</th><th>Quality</th><th>Notes</th></tr>
        ${sourceRows}</table>

      <h3 id="m-fuelmap">Fuel-type mapping (ENTSO-E → dashboard columns)</h3>
      <p>ENTSO-E production types do not map 1:1 onto Elexon fuel codes.
         The mapping and its known mismatches:</p>
      <table><tr><th>ENTSO-E production type</th><th>Dashboard column</th>
        <th>Mismatch / caveat</th></tr>${mapRows}</table>

      <h3 id="m-dq">Data quality (this zone)</h3>
      ${(meta.data_quality || []).length
        ? `<p>Gaps and absences below are the TSO's submission as published
             — verified against the raw ENTSO-E XML (variable-block periods
             are expanded per the spec before counting). Nothing is
             interpolated or hidden:</p>
           <ul>${meta.data_quality.map((n) => `<li>${n}</li>`).join("")}</ul>`
        : `<p>No reporting gaps detected in this window: every series the
             TSO publishes is complete.</p>`}

      <h3 id="m-gbonly">What stays GB-only for this zone, and why</h3>
      <ul>
        <li><b>Merit order</b> and <b>Spreads</b> — the SRMC cost model is
            GB-parameterised: gas SAP, UKA carbon and the efficiency
            assumptions are GB inputs, and ENTSO-E's unsplit "Fossil Gas"
            means no defensible CCGT/OCGT split exists. No per-zone SRMC
            assumptions have been defined yet, so these tabs are hidden
            rather than showing GB-costed panels for a non-GB market.</li>
        <li><b>Flows</b> — interconnector flows are a separate ENTSO-E
            document type not yet fetched; the zone schema has no
            interconnector columns, so the tab is hidden rather than
            rendering empty charts.</li>
        <li>The <b>overnight AI summary</b> and <b>observed dispatch</b>
            panels analyse the GB dataset only.</li>
      </ul>
      <p>Select GB in the zone switcher to see the full GB methodology.</p>`;
  }

  function renderMethodology() {
    if (State.get().zone !== "GB") { renderZoneMethodology(); return; }
    const meta = Data.meta;
    const cov = meta.coverage;
    const sourceRows = Object.values(meta.series).map((s) => `
      <tr><td><b>${s.name}</b></td><td>${s.source}</td>
      <td>${s.unit}</td><td>${s.resolution}</td>
      <td>${s.update_frequency}</td><td>${s.quality}</td>
      <td>${s.transformations}${s.notes ? "<br><i>" + s.notes + "</i>" : ""}</td>
      </tr>`).join("");

    document.getElementById("methodology-body").innerHTML = `
      <h3 id="m-window">Data window and coverage</h3>
      <p>Window: <code>${meta.window.start}</code> →
         <code>${meta.window.end}</code>, built
         <code>${meta.built_at}</code>. ${meta.timezone}</p>
      <p>Half-hourly coverage — demand ${(cov.demand * 100).toFixed(1)}%,
         price ${(cov.price * 100).toFixed(1)}%,
         solar ${(cov.solar * 100).toFixed(1)}%.
         Gas: ${cov.gas_days} days. UKA observed for
         ${cov.carbon_months_observed} months of the window; last published
         month <code>${cov.carbon_last_observed_month}</code> — later dates
         carry that value forward and are flagged as estimates.</p>

      <h3 id="m-sources">Sources, field mapping, transformations</h3>
      <table><tr><th>Series</th><th>Source / dataset</th><th>Unit</th>
        <th>Resolution</th><th>Updates</th><th>Quality</th>
        <th>Transformations &amp; notes</th></tr>${sourceRows}</table>

      <h3 id="m-price">Wholesale price (MID)</h3>
      <p>The Market Index Data price is the volume-weighted average of
         short-term trades reported by the appointed market index data
         providers (APX, N2EX). It is the public proxy for the GB spot price
         and feeds the imbalance price calculation. Day-ahead auction prices
         are commercial and not redistributed here.</p>

      <h3 id="m-residual">Residual load (estimated)</h3>
      <div class="formula">residual = demand(INDO) − wind(transmission)</div>
      <p>INDO is transmission-level demand, which is <b>already net of all
         embedded generation</b> — both solar and embedded wind suppress it in
         real time. Subtracting PV_Live solar on top would double-count it
         (an earlier version of this dashboard did exactly that, which is why
         residual load could go negative on sunny middays). The identity that
         makes this the correct national net load: underlying demand −
         all wind − all solar = (INDO + embedded gen) − all wind − all solar
         = INDO − transmission wind. Remaining limitation: embedded wind
         (~6 GW capacity) nets out <i>silently</i> inside INDO, so it is
         correctly absorbed here but invisible in gross wind output and
         share metrics — hence Estimated.</p>

      <h3 id="m-spark">Clean spark spread (estimated)</h3>
      <div class="formula">spark = price − gas_SAP / η − (EF_gas / η) · UKA − VOM</div>
      <p>Defaults: η = 50% (HHV), EF = 0.184 tCO2/MWh th, VOM = £3/MWh.
         Gas SAP is a within-day average, not the day-ahead curve a trader
         would hedge against; UKA is a monthly average forward-filled within
         the month. The result is a credible indicator of CCGT economics, not
         a tradable margin. All parameters adjustable on the Merit order tab;
         adjustments never modify stored historical data.</p>

      <h3 id="m-dark">Clean dark spread (proxy / derived)</h3>
      <div class="formula">dark = price − coal / η_coal − (EF_coal / η_coal) · UKA − VOM</div>
      <p>The GB-relevant coal benchmark (ICE API2, CIF ARA) is commercial
         data. The dashboard instead derives a transparent <b>futures-based
         proxy</b>, labelled Proxy / Derived:</p>
      <div class="formula">coal £/MWh th = (USD/t) ÷ FX(USD per GBP) ÷ 6.978 MWh th/t</div>
      <ul>
        <li><b>Coal price</b>: World Bank "Pink Sheet" monthly average of the
            Australian 6,000 kcal/kg FOB Newcastle <i>futures</i> price
            (USD/t) — public, monthly, ~2 working days after month end.</li>
        <li><b>FX</b>: Bank of England daily USD/GBP spot (XUDLUSS), averaged
            over each calendar month.</li>
        <li><b>Energy content</b>: 6,000 kcal/kg = 25.12 GJ/t = 6.978 MWh
            thermal per tonne.</li>
      </ul>
      <p>Caveats: Newcastle FOB is a different basis from API2 CIF ARA
         (freight and quality differ), so levels track but do not equal the
         European benchmark; the monthly value is forward-filled within and
         beyond the month (flagged <code>coal_ffill</code>). A manually
         entered coal price overrides the proxy and relabels the panel
         Assumption. EF_coal default 0.34 tCO2/MWh th.</p>

      <h3 id="m-merit">SRMC cost model (estimated)</h3>
      <p>Technology SRMC ranges are computed from the latest observed gas SAP
         and UKA price with stated efficiency spans — they are cost estimates,
         not observed bids. This model drives the merit-order curve and the
         cost attribution in the observed-dispatch tooltips. Biomass fuel
         costs are commercial; a broad published range is shown and marked as
         assumed. (An earlier per-technology bar view of these ranges was
         removed as redundant — the merit-order curve shows the same
         information at tranche granularity plus the demand and clearing
         lines.)</p>

      <h3 id="m-meritcurve">Merit order curve (estimated)</h3>
      <p>The curve uses the SRMC cost model above. Each
         technology's SRMC range is split into 0.5 GW capacity tranches with
         cost rising linearly across the technology (efficient units first);
         all tranches are then sorted by SRMC, so the stack is contiguous and
         monotonically non-decreasing — the conventional merit-order
         geometry. Technologies interleave where their cost ranges overlap.
         Capacity is a stated proxy, not registered capacity:</p>
      <ul>
        <li><b>Dispatchables</b> (nuclear, biomass, hydro, CCGT, OCGT, coal):
            98th percentile of observed half-hourly output over the dataset
            window — what the fleet has actually delivered.</li>
        <li><b>Wind and solar</b>: latest observed output, since they are
            must-run price-takers whose available capacity at any moment is
            their output.</li>
      </ul>
      <p>The vertical line is the latest demand minus net imports — what GB
         plant must serve now. The implied clearing price interpolates the
         curve at that point; comparing it with the observed price tests the
         cost model against the market. Pumped storage, oil and "other" are
         excluded (no defensible SRMC benchmark); interconnectors are netted
         off the demand line rather than stacked.</p>

      <h3 id="m-bmu">Observed dispatch by unit (observed volumes, estimated
         costs; beta)</h3>
      <p>A dispatch curve built from physical notifications (PN) per BM Unit
         for the most recent complete settlement period, from the Elexon
         Insights PN dataset joined to the BM Unit registry, refreshed by
         <code>etl/build_bmu_snapshot.py</code>. Each block is one unit:
         width is its notified MW (time-weighted mean of the level profile
         across the half-hour — <b>Observed</b>); height is its technology
         cluster's SRMC <em>midpoint</em> from the cost model above
         (<b>Estimated</b>). Units are sorted cheapest-first on the same axes
         as the modelled merit-order curve, so modelled and observed dispatch
         can be compared directly. Read the caveats before leaning on it:</p>
      <ul>
        <li><b>PN is notified intent, not metered output</b> — units can and
            do deviate from their final physical notifications, and the data
            carries no prices, so this is not a bid stack and cannot replace
            the modelled merit curve.</li>
        <li><b>The price axis is a cluster attribution, not unit data.</b>
            Every unit of a technology sits at the same midpoint; within a
            cluster, larger units are drawn first as a display convention
            only. No unit-level costs exist in free data.</li>
        <li><b>Units without an SRMC benchmark are not plotted</b> —
            unclassified units (no registry fuel type: mostly batteries, DSR
            and small aggregations) plus pumped storage, oil and "other"
            (no defensible cost benchmark). Their count and GW are stated
            under the caption rather than silently dropped, alongside the
            classified share of notified MW.</li>
        <li><b>Also excluded</b>: interconnector units (flows, not dispatch —
            see the Flows tab), units notifying zero, and charging/pumping
            units (negative levels).</li>
      </ul>

      <h3 id="m-netload">Price vs net load (estimated)</h3>
      <div class="formula">net load = demand(INDO) − wind(transmission)</div>
      <p>Each scatter point is one observed half-hourly price against derived
         net load — the demand left for dispatchable plant, the standard
         system-tightness variable. Solar is <b>not</b> subtracted: INDO is
         already net of embedded solar (see residual load above); PV_Live
         solar is shown in the tooltip for context only. The optional overlay
         shows the median price per 2 GW bin (bins with under 12 half-hours
         are dropped).</p>

      <h3 id="m-generation">Generation and flows</h3>
      <p>Elexon FUELHH covers transmission-connected plant; embedded solar
         comes from PV_Live (model-estimated from a metered sample — the GB
         standard). Embedded wind is not included anywhere: published GB
         "wind" here means transmission-metered wind. Interconnector flows are
         metered (positive = import). Greenlink/Viking appear from their
         respective commissioning dates.</p>

      <h3 id="m-lowcarbon">Low-carbon share (estimated)</h3>
      <div class="formula">low_carbon = (nuclear + biomass + hydro + pumped storage + wind + solar) / total supply</div>
      <p>Biomass is included per GB grid-intensity convention; imports are
         counted in the denominator but excluded from the numerator because
         their origin mix is not observed. Both choices are debatable — hence
         Estimated.</p>

      <h3 id="m-overnight">Overnight summary (AI-generated)</h3>
      <p>The panel below the KPI strip is written by an LLM (the
         <code>dashboard-watcher</code> agent, invoked headlessly by
         <code>ops/run_overnight_summary.sh</code> during the daily refresh).
         It compares the last 48 hours against a 14–30 day baseline,
         flags |z|&nbsp;&gt;&nbsp;2 as notable and reports data-quality flags
         separately. It is an <b>interpretation of the published dataset,
         not a data series</b> — hence the distinct dashed styling and
         AI-generated badge. Hypotheses are phrased as "consistent with";
         the agent is instructed never to assert market events it cannot
         support from the data. A failed generation leaves the previous
         summary in place; if none exists the panel says so rather than
         guessing.</p>

      <h3 id="m-refresh">Refresh process</h3>
      <p><code>python etl/build_dataset.py --incremental</code> re-fetches
         the last two stored days plus anything newer (upstream revisions are
         overwritten), merges onto the published dataset, keeps the window
         rolling at 365 days and publishes atomically behind a validation
         guard — a failed run leaves the live files untouched. A versioned
         <code>manifest.json</code> cache-busts the data files. A launchd job
         (installed via <code>ops/install_schedule.sh</code>) runs this daily
         at 07:00 local time; missed runs fire on wake — see
         <code>ops/README.md</code>. The footer's "Dataset built" timestamp
         is the staleness signal; a full rebuild is
         <code>--days 365</code>.</p>

      <h3 id="m-limits">Known limitations</h3>
      <ul>
        <li>MID is a proxy, not the day-ahead auction price.</li>
        <li>UKA prices are monthly averages with a publication lag.</li>
        <li>Gas SAP is within-day, lagging the forward curve in fast markets.</li>
        <li>No unit commitment, network constraints or balancing actions are
            modelled anywhere in this app.</li>
        <li>Embedded wind is invisible to all sources used.</li>
      </ul>`;
  }

  /* ---------------- CSV export ---------------- */

  function exportCsv() {
    const st = State.get();
    const { fromTs, toTs, fromIso, toIso } = State.window();
    const sec = State.bucketSeconds();
    let columns, name;

    if (st.tab === "spreads" || st.tab === "merit") {
      const a = st.assumptions;
      const d = Data.dailySlice(fromIso, toIso,
        ["price", "gas_sap", "carbon_uka_month", "carbon_ffill",
         "coal_proxy_gbp_mwh", "coal_ffill"]);
      columns = {
        date: d.d, price_gbp_mwh: d.price, gas_sap_gbp_mwh_th: d.gas_sap,
        carbon_uka_gbp_t: d.carbon_uka_month, carbon_is_ffill: d.carbon_ffill,
        clean_spark_gbp_mwh: Metrics.cleanSparkSpread(d.price, d.gas_sap,
          d.carbon_uka_month, { eta: a.eta, efGas: a.efGas, vom: a.vom }),
      };
      const coal = State.coalInfo();
      if (coal) {
        const coalInput = coal.source === "manual"
          ? coal.value : d.coal_proxy_gbp_mwh;
        columns.coal_proxy_gbp_mwh_th = coal.source === "manual"
          ? d.d.map(() => coal.value) : d.coal_proxy_gbp_mwh;
        columns.coal_is_ffill = coal.source === "manual"
          ? d.d.map(() => "") : d.coal_ffill;
        columns.clean_dark_gbp_mwh = Metrics.cleanDarkSpread(
          d.price, d.carbon_uka_month, coalInput,
          { etaCoal: a.etaCoal, efCoal: a.efCoal, vomCoal: a.vomCoal });
      }
      name = `gb_spreads_${fromIso}_${toIso}.csv`;
    } else {
      // Zone-aware export: whatever fuel columns the active zone actually
      // carries (Data.* is already swapped per zone by Data.load), plus
      // net imports only where interconnector data exists (GB). Price
      // header carries the zone's settlement currency, not hardcoded GBP.
      const zone = st.zone.toLowerCase();
      const curCode = (st.zone === "GB" ? "GBP"
        : (Data.meta.currency || "EUR")).toLowerCase();
      // hasSignal excludes absent AND constant-zero placeholder columns
      // (e.g. IE solar) — their zeros are TSO artefacts, not output.
      const keys = ["price", "demand",
        ...Data.STACK_ORDER.filter((k) => Data.hasSignal(k)),
        ...(Object.keys(Data.INTERCONNECTORS).some((k) => Data.hh[k])
          ? ["netImports"] : [])];
      columns = {};
      keys.forEach((k) => {
        const agg = Data.aggregate(k, fromTs, toTs, sec);
        if (!columns.timestamp_utc) {
          columns.timestamp_utc = agg.t.map((t) =>
            new Date(t).toISOString());
        }
        const header = k === "price" ? `price_${curCode}_mwh`
          : k === "netImports" ? "net_imports_mw" : k.toLowerCase();
        columns[header] = agg.v.map((v) =>
          v == null ? null : +v.toFixed(2));
      });
      name = `${zone}_market_${fromIso}_${toIso}_` +
        `${State.effectiveResolution()}.csv`;
    }

    const blob = new Blob([Metrics.toCsv(columns)], { type: "text/csv" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = name;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  return { renderGlance, renderOvernight, renderKpis, renderAssumptions,
           renderMethodology, exportCsv };
})();
